[package]
name = "elrond_wyvern_project_smart_contract-meta"
version = "1.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.elrond_wyvern_project_smart_contract]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.30.0"
